/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CheckpointsIndexImport } from './routes/checkpoints.index'
import { Route as CheckpointsCreateImport } from './routes/checkpoints.create'
import { Route as CheckpointsCheckpointIdImport } from './routes/checkpoints.$checkpointId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CheckpointsIndexRoute = CheckpointsIndexImport.update({
  path: '/checkpoints/',
  getParentRoute: () => rootRoute,
} as any)

const CheckpointsCreateRoute = CheckpointsCreateImport.update({
  path: '/checkpoints/create',
  getParentRoute: () => rootRoute,
} as any)

const CheckpointsCheckpointIdRoute = CheckpointsCheckpointIdImport.update({
  path: '/checkpoints/$checkpointId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/checkpoints/$checkpointId': {
      id: '/checkpoints/$checkpointId'
      path: '/checkpoints/$checkpointId'
      fullPath: '/checkpoints/$checkpointId'
      preLoaderRoute: typeof CheckpointsCheckpointIdImport
      parentRoute: typeof rootRoute
    }
    '/checkpoints/create': {
      id: '/checkpoints/create'
      path: '/checkpoints/create'
      fullPath: '/checkpoints/create'
      preLoaderRoute: typeof CheckpointsCreateImport
      parentRoute: typeof rootRoute
    }
    '/checkpoints/': {
      id: '/checkpoints/'
      path: '/checkpoints'
      fullPath: '/checkpoints'
      preLoaderRoute: typeof CheckpointsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CheckpointsCheckpointIdRoute,
  CheckpointsCreateRoute,
  CheckpointsIndexRoute,
})

/* prettier-ignore-end */
