/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateCheckpointImport } from './routes/create-checkpoint'
import { Route as CheckpointsImport } from './routes/checkpoints'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CreateCheckpointRoute = CreateCheckpointImport.update({
  path: '/create-checkpoint',
  getParentRoute: () => rootRoute,
} as any)

const CheckpointsRoute = CheckpointsImport.update({
  path: '/checkpoints',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/checkpoints': {
      id: '/checkpoints'
      path: '/checkpoints'
      fullPath: '/checkpoints'
      preLoaderRoute: typeof CheckpointsImport
      parentRoute: typeof rootRoute
    }
    '/create-checkpoint': {
      id: '/create-checkpoint'
      path: '/create-checkpoint'
      fullPath: '/create-checkpoint'
      preLoaderRoute: typeof CreateCheckpointImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CheckpointsRoute,
  CreateCheckpointRoute,
})

/* prettier-ignore-end */
